name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Test
        run: mvn test -B
        env:
          RAMAccessKeyId: ${{ secrets.RAMACCESSKEYID }}
          RAMAccessKeySecret: ${{ secrets.RAMACCESSKEYSECRET }}
          roleArn: ${{ secrets.ROLEARN }}
      - name: CodeCov
        run: bash <(curl -s https://codecov.io/bash) -cF unittest